### ISSUE TITLE
Convert unit tests from cppunit to googletest

### ISSUE THREAD

**Issue by dschwen** [idaholab/magpie#282]
Unit tests are currently crashing, (@rwcarlsen or @brianmoose) I suspect we're left alone here because we're still on cppunit. Let's migrate the tests to gtest.

**Comment by brianmoose** [comment]
There are other apps that still have cppunit unit tests that are working fine (like rattlesnake/yak/unit)

**Comment by dschwen** [comment]
@brianmoose, there was a bug that I could identify after converting to gtest and running in dbg, which just happened not to crash the tests so far. Something must have changed. Anyhow, there is a PR that fixes this now.
