### ISSUE TITLE
Change user interface for site_volume & concentration/density specs

### ISSUE THREAD

**Issue by snschune** [idaholab/magpie#347]
`site_volume` is always in nano-meters so if mesh units are not nano-meters and number densities are used as variables in the rasterizer, the `site_volume` has to be set to some `10^n` where `n` is usually not zero. Documentation is also currently incorrect.

Plan is to add an enum that describes the physical meaning of the rasterizer variables. If they are concentrations, then `site_volume` must be set, if they are number densities, `site_volume` is set correctly by the rasterizer.

**Comment by dschwen** [comment]
Closed by #350
