### ISSUE TITLE
Example does not have registered objects 

### ISSUE THREAD

**Issue by amjokisaari** [idaholab/magpie#406]
In examples/grand_potential_magpie/GP_MAGPIE_density.i, user receives a message that the GrandPotentialRecombination object is not registered.  (I'm guessing that's in Marmot?).  It's probably a good idea to not have examples from being dependent upon a non-open-source code.

**Comment by dschwen** [comment]
Yes the examples are not guaranteed with work with vanilla Magpie. Magpie is to be used like a module in any MOOSE app you want to augment with radiation effects calculations. We are testing the examples for syntax and the `tests` files have the appropriate restrictions.

Marmot would not be an appropriate place for such an example either. I'll close this as there isn't a clear course of action to address this.

**Comment by amjokisaari** [comment]
Ok, got it.  I can start adding doco as we go through these discussions so
that it's there for new users.

**Comment by snschune** [comment]
> We are testing the examples for syntax and the tests files have the appropriate restrictions.

Do we have the appropriate test targets? How can it be checked for syntax if the syntax isn't known due to missing objects?
